import 'package:lucide_icons_flutter/lucide_icons.dart';
import 'package:flutter/widgets.dart';
import '../l10n/app_localizations.dart';

IconData getLegIcon(String mode) {
  switch (mode) {
    case 'WALK':
      return LucideIcons.footprints;
    case 'BIKE':
      return LucideIcons.bike;
    case 'RENTAL':
      return LucideIcons.carTaxiFront;
    case 'CAR':
      return LucideIcons.carFront;
    case 'CAR_PARKING':
      return LucideIcons.parkingMeter;
    case 'CAR_DROPOFF':
      return LucideIcons.parkingMeter;
    case 'ODM':
      return LucideIcons.carTaxiFront;
    case 'FLEX':
      return LucideIcons.route;
    case 'TRANSIT':
      return LucideIcons.network;
    case 'OTHER':
      return LucideIcons.circle;
    case 'TRAM':
      return LucideIcons.tramFront;
    case 'SUBWAY':
      return LucideIcons.squareArrowDown;
    case 'FERRY':
      return LucideIcons.ship;
    case 'AIRPLANE':
      return LucideIcons.plane;
    case 'SUBURBAN':
      return LucideIcons.tramFront;
    case 'BUS':
      return LucideIcons.busFront;
    case 'COACH':
      return LucideIcons.bus;
    case 'RAIL':
      return LucideIcons.trainFront;
    case 'HIGHSPEED_RAIL':
      return LucideIcons.trainFront;
    case 'LONG_DISTANCE':
      return LucideIcons.trainFront;
    case 'NIGHT_RAIL':
      return LucideIcons.trainFront;
    case 'REGIONAL_FAST_RAIL':
      return LucideIcons.trainFront;
    case 'REGIONAL_RAIL':
      return LucideIcons.trainFront;
    case 'CABLE_CAR':
      return LucideIcons.cableCar;
    case 'AERIAL_LIFT':
      return LucideIcons.cableCar;
    case 'FUNICULAR':
      return LucideIcons.cableCar;
    case 'AREAL_LIFT':
      return LucideIcons.cableCar;
    case 'METRO':
      return LucideIcons.squareArrowDown;
    default:
      return LucideIcons.circleQuestionMark;
  }
}

String getTransitModeName(AppLocalizations l10n, String mode) {
  switch (mode) {
    case 'WALK':
      return l10n.utilsLegHelperTransitionModeNameWalk;
    case 'BIKE':
      return l10n.utilsLegHelperTransitionModeNameBike;
    case 'RENTAL':
      return l10n.utilsLegHelperTransitionModeNameRental;
    case 'CAR':
      return l10n.utilsLegHelperTransitionModeNameCar;
    case 'CAR_PARKING':
      return l10n.utilsLegHelperTransitionModeNameCarParking;
    case 'CAR_DROPOFF':
      return l10n.utilsLegHelperTransitionModeNameCarDropoff;
    case 'ODM':
      return l10n.utilsLegHelperTransitionModeNameOnDemand;
    case 'FLEX':
      return l10n.utilsLegHelperTransitionModeNameFlexibleService;
    case 'TRANSIT':
      return l10n.utilsLegHelperTransitionModeNameTransit;
    case 'TRAM':
      return l10n.utilsLegHelperTransitionModeNameTram;
    case 'SUBWAY':
      return l10n.utilsLegHelperTransitionModeNameSubway;
    case 'FERRY':
      return l10n.utilsLegHelperTransitionModeNameFerry;
    case 'AIRPLANE':
      return l10n.utilsLegHelperTransitionModeNameAirplane;
    case 'SUBURBAN':
      return l10n.utilsLegHelperTransitionModeNameSuburban;
    case 'BUS':
      return l10n.utilsLegHelperTransitionModeNameBus;
    case 'COACH':
      return l10n.utilsLegHelperTransitionModeNameCoachBus;
    case 'RAIL':
      return l10n.utilsLegHelperTransitionModeNameTrain;
    case 'HIGHSPEED_RAIL':
      return l10n.utilsLegHelperTransitionModeNameHighSpeedTrain;
    case 'LONG_DISTANCE':
      return l10n.utilsLegHelperTransitionModeNameTrain;
    case 'NIGHT_RAIL':
      return l10n.utilsLegHelperTransitionModeNameNightTrain;
    case 'REGIONAL_FAST_RAIL':
      return l10n.utilsLegHelperTransitionModeNameExpressTrain;
    case 'REGIONAL_RAIL':
      return l10n.utilsLegHelperTransitionModeNameTrain;
    case 'CABLE_CAR':
      return l10n.utilsLegHelperTransitionModeNameCableCar;
    case 'AERIAL_LIFT':
      return l10n.utilsLegHelperTransitionModeNameAerialLift;
    case 'FUNICULAR':
      return l10n.utilsLegHelperTransitionModeNameFunicular;
    case 'AREAL_LIFT':
      return l10n.utilsLegHelperTransitionModeNameArealLift;
    case 'METRO':
      return l10n.utilsLegHelperTransitionModeNameMetro;
    case 'OTHER':
      return l10n.utilsLegHelperTransitionModeNameOther;
    default:
      return mode;
  }
}
